# Generated by Django 5.2.3 on 2025-06-30 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cooking_method',
            field=models.CharField(choices=[('boil', 'Варка'), ('fry', 'Жарка'), ('bake', 'Запекание'), ('stew', 'Тушение'), ('grill', 'Гриль'), ('steam', 'Пар'), ('raw', 'Без термообработки'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Метод приготовления'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='main_ingredient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_recipes', to='recipes.ingredient', verbose_name='Главный ингредиент'),
        ),
    ]
